import os
import sys
import json
import uuid
import urllib.request
import urllib.error
from datetime import datetime, timezone

def main():
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    pr_number = os.environ.get("PR_NUMBER")

    if not all([token, repo, pr_number]):
        print("Error: Missing required environment variables (GITHUB_TOKEN, GITHUB_REPOSITORY, PR_NUMBER).")
        sys.exit(1)

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    base_url = f"https://api.github.com/repos/{repo}"

    # 1. Fetch PR details and diff
    try:
        pr_url = f"{base_url}/pulls/{pr_number}"
        
        # Get PR JSON
        req = urllib.request.Request(pr_url, headers=headers)
        with urllib.request.urlopen(req) as response:
            pr_data = json.loads(response.read().decode("utf-8"))
            
        # Get PR diff
        diff_headers = headers.copy()
        diff_headers["Accept"] = "application/vnd.github.v3.diff"
        diff_req = urllib.request.Request(pr_url, headers=diff_headers)
        with urllib.request.urlopen(diff_req) as response:
            pr_diff = response.read().decode("utf-8")
            
        # Get PR comments
        comments_url = f"{base_url}/issues/{pr_number}/comments"
        comments_req = urllib.request.Request(comments_url, headers=headers)
        with urllib.request.urlopen(comments_req) as response:
            comments_data = json.loads(response.read().decode("utf-8"))
            
    except urllib.error.URLError as e:
        print(f"Failed to fetch PR data: {e}")
        if hasattr(e, 'read'):
            print(e.read().decode('utf-8'))
        sys.exit(1)

    print(f"Successfully fetched PR #{pr_number} data.")

    # 2. Generate mocked review JSON
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y%m%d")
    # Generate 3 random digits
    random_str = str(uuid.uuid4().int)[:3].zfill(3)
    review_id = f"REV-{date_str}-{random_str}"
    
    # Participants can be the PR author and reviewers (mocked)
    author = pr_data.get("user", {}).get("login", "unknown_author")
    participants = [author, "github-actions[bot]"]
    
    review_data = {
        "review_id": review_id,
        "timestamp": now.isoformat(),
        "participants": participants,
        "task_type": "feature_review",
        "decisions": [
            "Approved the PR based on automated checks.",
            "Mocked decision for testing."
        ],
        "success_factors": ["Clean diff", "No linting errors"],
        "failure_reasons": [],
        "best_practices": ["Included tests", "Clear commit messages"],
        "action_items": ["Monitor deployment", "Update documentation"],
        "status": "active"
    }

    # 3. Save to .storage/reviews/
    storage_dir = os.path.join(".storage", "reviews")
    os.makedirs(storage_dir, exist_ok=True)
    
    file_path = os.path.join(storage_dir, f"{review_id}.json")
    try:
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(review_data, f, indent=2)
        print(f"Saved review to {file_path}")
    except IOError as e:
        print(f"Failed to save review file: {e}")
        sys.exit(1)

    # 4. Post comment back to PR
    decisions_text = "\n".join(f"- {d}" for d in review_data["decisions"])
    action_items_text = "\n".join(f"- {a}" for a in review_data["action_items"])
    
    comment_body = f"""### Automated PR Review Summary

**Review ID:** `{review_id}`
**Status:** {review_data['status']}
**Task Type:** {review_data['task_type']}

**Decisions:**
{decisions_text}

**Action Items:**
{action_items_text}

*This is an automated review generated by the Issue Trackers loop.*
"""
    
    comment_payload = json.dumps({"body": comment_body}).encode("utf-8")
    post_comment_req = urllib.request.Request(
        comments_url, 
        data=comment_payload, 
        headers=headers, 
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(post_comment_req) as response:
            if response.status == 201:
                print("Successfully posted comment to PR.")
            else:
                print(f"Unexpected status code when posting comment: {response.status}")
    except urllib.error.URLError as e:
        print(f"Failed to post comment: {e}")
        if hasattr(e, 'read'):
            print(e.read().decode('utf-8'))
        sys.exit(1)

if __name__ == "__main__":
    main()
